name: BierRuestung
version: 1.1.0
main: de.bierrang.plugin.BierRuestung
api-version: '1.21'
commands:
  armorGUI:
    description: Öffnet das Admin Menü für Rüstung
    usage: /armorGUI
  beaconbook:
    description: Gibt Spezialbücher
    usage: /beaconbook <type>
permissions:
  bierarmor.admin:
    default: op
